# site settings
title: HackHaus
subtitle: Chicago's Curious Coworking
email: info@hackha.us
description: A space for thinkers and thinkerers to collaborate on sovereign identity, digital rights, and decentralization.
baseurl: # the subpath of your site, e.g. /blog
url: "https://hackha.us" # the base hostname & protocol for your site
author:
street_address: 4649 N Broadway St
city: Chicago
state: IL
zip_code: 60640
country: United States of America
phone: +1 (312) 620-4649

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10

# social settings
500px_url:
facebook_url: https://www.facebook.com/Hackhaus-108027063880284/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/hackhaus
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

call_to_action: "Join Us"
get_started: "/join.html"

collections:
    members:
      output: false
